name: fryad_calculator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # Widened constraint for better compatibility

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # CORE & UI
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0

  # FUNCTIONALITY
  math_expressions: ^2.5.0
  share_plus: ^9.0.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.12.0

  # LOCAL STORAGE & FILE HANDLING
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  csv: ^6.0.0
  file_picker: ^8.0.5

  # CHARTS
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
