# Name of the workflow
name: Build and Release Android APK

# This workflow now runs ONLY when you push a new tag (e.g., v1.0.1)
on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0, v1.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      # This is the NEW step that creates the release
      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          # This makes the release body whatever you wrote in your tag message
          body_path: ${{ github.event.head_commit.message }}
          files: build/app/outputs/flutter-apk/app-release.apk